version: '3.8'

services:
  nestapp:
    build: .
    container_name: nest_app
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:password@mysql:3306/mydb
    depends_on:
      - mysql
    command: npm run start:dev

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3307"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
